### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [credo7/Async_API_sprint_1#21]
Хорошая работа 👍 Но, все же, есть несколько моментов, требующих внимания:
1. [Этот](https://github.com/credo7/Async_API_sprint_1/blob/c1047471e83d46ddcc7c488a1efeae7d13c6184a/docker-compose.yml#L31), [это](https://github.com/credo7/Async_API_sprint_1/blob/c1047471e83d46ddcc7c488a1efeae7d13c6184a/docker-compose.yml#L44) и [этот](https://github.com/credo7/Async_API_sprint_1/blob/c1047471e83d46ddcc7c488a1efeae7d13c6184a/docker-compose.yml#L72) порты не нужно выставлять наружу. В части безопасности приложения это не очень хорошо. Кстати, названия сервисов немного странные, с суффиксом `_test`. Вот это поможет https://devilbox.readthedocs.io/en/latest/configuration-files/docker-compose-override-yml.html
2. Этот сервис выдачи контента, как и остальные сервисы кинотеатра, доступные пользователю, должен отдаваться через nginx.
3. В продакшене не рекомендуется запускать код через uvicorn напрямую, вот тут про это написано несколько слов https://www.uvicorn.org/deployment/#gunicorn.
4. Файл `etl/.env.example` используется во всех сервисах. Его лучше расположить в корне приложения.
5. В FastAPI появилась более удобная альтернатива для обработки событий **@app.on_event('startup')** и **@app.on_event('shutdown')** https://fastapi.tiangolo.com/advanced/events/#lifespan. Можно попробовать использовать в проекте.
6. Эта строка лишняя:
https://github.com/credo7/Async_API_sprint_1/blob/c1047471e83d46ddcc7c488a1efeae7d13c6184a/src/main.py#L23
7. Конфиг `src/core/config.py` правильнее было оформить в виде класса:
      ```python
      from pydantic import BaseSettings
      
      class Settings(BaseSettings):
          project_name: str = 'Some project name'
          redis_host: str = ...
          redis_port: int = ...
          elastic_host: str = Field(..., env='ELASTIC_HOST_NAME')
          elastic_port: int = Field(9200, env='ELASTIC_PORT')
      
      settings = Settings()
      ```
      и затем использовать инстанс конфига setting в разных частях приложения. Плюс такого подхода в том, что происходит валидация типов переменных окружения при помощи pydantic. Также при создании инфраструктуры под тесты, можно будет наследоваться от этого класса и создать отдельный тестовый конфиг со своими переменными окружения. Подробнее https://pydantic-docs.helpmanual.io/usage/settings/
      В моем примере BaseSettings:
      - присвоит в поле project_name значение переменной PROJECT_NAME, а если ее нет, то даст значение по умолчанию 'Some project name'
      - redis_host мы сделали обязательным полем (... - служебный символ), если не будет переменной окружения REDIS_HOST, то проект не заведется
      - elastic_host мы сделали обязательным и явно указали имя переменной окружения, т.к. она отличается от имени поля
      - elastic_port так же как и с хостом, но указали и значение по умолчанию
8. Начиная с python 3.10 можно не использовать Optional из модуля typing. В новом синтаксисе можно [использовать](https://github.com/credo7/Async_API_sprint_1/blob/c1047471e83d46ddcc7c488a1efeae7d13c6184a/src/db/redis.py#L4) вот такую конструкцию:  `redis: Redis | None = None`
9. С версии python 3.9 для стандартных [коллекций](https://github.com/credo7/Async_API_sprint_1/blob/c1047471e83d46ddcc7c488a1efeae7d13c6184a/src/models/film.py#L33) больше не нужен модуль typing. И [это](https://github.com/credo7/Async_API_sprint_1/blob/c1047471e83d46ddcc7c488a1efeae7d13c6184a/src/models/film.py#L33) можно записать так: 
      ```python
      actors: list[MoviePerson] | None
      ```
      https://docs.python.org/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections
10. В `src/models` не помешает подружить с orjson все модели.
11. Зачем 3 раза переопределяете одну константу?
https://github.com/credo7/Async_API_sprint_1/blob/c1047471e83d46ddcc7c488a1efeae7d13c6184a/src/services/film.py#L14
https://github.com/credo7/Async_API_sprint_1/blob/c1047471e83d46ddcc7c488a1efeae7d13c6184a/src/services/genre.py#L13
https://github.com/credo7/Async_API_sprint_1/blob/c1047471e83d46ddcc7c488a1efeae7d13c6184a/src/services/person.py#L13
12. Swagger документация ваших сервисов выглядит максимально куцей, давайте добавим хотя бы description, подробнее тут: https://fastapi.tiangolo.com/tutorial/path-operation-configuration/?h=description#summary-and-description
13. Нет эндпоинта, который требуется в техническом задании:
      ![Снимок экрана 2023-08-13 в 23 52 42](https://github.com/credo7/Async_API_sprint_1/assets/73478414/68d08722-7428-4f03-99dc-aa2622b7203a)

**Comment by credo7** [comment]
5. Спасибо об информировании про FastAPI lifespan, но пока командой решили оставить текущий вариант.
10. pydantic V2 и в себе уже имеет orjson или даже быстрее (по тестам), а прошлый функционал они удалили https://github.com/pydantic/pydantic/discussions/6388

**Comment by BigDeepBlue** [comment]
> 6\. pydantic V2 и в себе уже имеет orjson или даже быстрее (по тестам), а прошлый функционал они удалили [Orjson in Pydantic V2 pydantic/pydantic#6388](https://github.com/pydantic/pydantic/discussions/6388)

Не обратил внимание на версию  pydantic. Да, v2 написан на Rust и очень быстр.

**Comment by BigDeepBlue** [comment]
LGTM
