### ISSUE TITLE
Доработать ETL для записи в ES данных персоналий

### ISSUE THREAD

**Issue by credo7** [credo7/Async_API_sprint_1#3]
Добавить новый ETL пайплайн, в котором создается и заполняется индекс persons из всех людей, которые есть в фильмах. Плоский индекс без денормализованных данных. Хранить роли и ссылки на фильмы не нужно.

Оценка: 5

**Comment by chingisdev** [comment]
Все в одной ветке 4/feat-etl-genres, под один ишью
