### ISSUE TITLE
Доработать ETL для записи в ES данных жанров

### ISSUE THREAD

**Issue by credo7** [credo7/Async_API_sprint_1#4]
Добавить новый ETL пайплайн, в котором создается и заполняется индекс genres из всех жанров, которые есть в фильмах. Плоский индекс без денормализованных данных. Хранить ссылки на фильмы не нужно.

Оценка: 5

**Comment by chingisdev** [comment]
Все в одной ветке 4/feat-etl-genres, под один ишью
